name: Deploy Frontend

on:
  push:
    branches:
      - main
    paths:
      - "client/**"

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7

      - uses: actions/setup-node@v6
        with:
          node-version: "20"
          cache: "npm"
          cache-dependency-path: client/package-lock.json

      - name: Install dependencies
        working-directory: client
        run: npm ci

      - name: Build
        working-directory: client
        run: npm run build
        env:
          VITE_WS_URL: ${{ vars.VITE_WS_URL }}

      - uses: aws-actions/configure-aws-credentials@v6
        with:
          role-to-assume: arn:aws:iam::864617344104:role/samether-dev-github-actions-role
          aws-region: ap-northeast-1

      - name: Upload to S3
        run: aws s3 sync client/dist/ s3://samether-dev-frontend-assets/ --delete

      - name: Invalidate CloudFront
        run: aws cloudfront create-invalidation --distribution-id E103UZ2786IGBW --paths "/*" #変更
